### ISSUE TITLE
Warning about `componentWillReceiveProps` in React's Strict Mode

### ISSUE THREAD

**Issue by ulrichb** [moroshko/react-autosuggest#624]
React's [Strict Mode](https://reactjs.org/docs/strict-mode.html) warns about "Unsafe lifecycle methods were found within a strict-mode tree".

> `componentWillReceiveProps`: Please update the following components to use static getDerivedStateFromProps instead.

https://github.com/moroshko/react-autosuggest/blob/d626cef720df0ed5a4c7df4d539836b86bda6afa/src/Autosuggest.js#L124-L143

**Comment by ulrichb** [comment]
Now with React 16.9 it's even a non-strict mode warning ...

**Comment by Kove11** [comment]
Any update on this @moroshko ?

**Comment by valentyna-refundit** [comment]
Still very relevant, looking forward to updates

**Comment by rlueder** [comment]
Here's a PR that should take care of it: https://github.com/moroshko/react-autosuggest/pull/681

**Comment by aberezkin** [comment]
fixed in #681

**Comment by wzijden** [comment]
@aberezkin this should not have been closed. It resolves https://github.com/moroshko/react-autosuggest/issues/670, but not this one. A warning is still shown in React's strictmode:
```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code.
```

**Comment by aberezkin** [comment]
Can someone work on this?

**Comment by adi518** [comment]
> Fixed in #681

It doesn't fix this warning for strict mode.

**Comment by reft** [comment]
still not fixed¿¿
